# Generated by Django 4.2.2 on 2023-06-30 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cohort',
            name='subject',
            field=models.CharField(choices=[('SEI', 'Software Engineering Immersive'), ('UXDI', 'User Experience Development Immersive'), ('DSI', 'Data Science Immersive')], max_length=5),
        ),
    ]
